---
- name: Config Nagios | copy common Serverplugins
  copy: src=/home/ansible/ansible/teams/charlie/common/Nagios/Server/ServerPlugins/ dest=/usr/lib64/nagios/plugins owner=nagios group=nagios mode=0755
  become: yes

- name: Config Nagios | copy common 3rdParty
  copy: src=/home/ansible/ansible/teams/charlie/common/Nagios/Server/3rdParty/ dest=/usr/lib64/nagios/plugins owner=nagios group=nagios mode=0755
  become: yes

- name: Config Nagios | copy common pagerduty
  copy: src=/home/ansible/ansible/teams/charlie/common/Nagios/Server/pagerduty.cfg dest=/etc/nagios/objects/pagerduty.cfg
  become: yes
  notify:
    - reload nagios

- name: Config Nagios | copy common commands
  copy: src=/home/ansible/ansible/teams/charlie/common/Nagios/Server/commands.cfg dest=/etc/nagios/objects/commands.cfg
  become: yes
  notify:
    - reload nagios

- name: Config Nagios | copy nagios config
  copy: src={{ l3source_base }}/{{ customer }}/nagios_config/objects/ dest=/etc/nagios/objects owner=nagios group=nagios mode=0644
  become: yes
  notify:
    - reload nagios

- name: Config Nagios | copy cgi.cfg config  
  copy: src={{ l3source_base }}/{{ customer }}/nagios_config/cgi.cfg dest=/etc/nagios/cgi.cfg owner=nagios group=nagios mode=0644
  become: yes
  notify:
    - reload nagios

- name: Config Nagios | copy nagios.cfg config
  copy: src={{ l3source_base }}/{{ customer }}/nagios_config/nagios.cfg dest=/etc/nagios/nagios.cfg owner=nagios group=nagios mode=0644
  become: yes
  notify:
    - reload nagios

- name: Config Nagios | copy resource.cfg config
  copy: src={{ l3source_base }}/{{ customer }}/nagios_config/resource.cfg dest=/etc/nagios/private/resource.cfg owner=nagios group=nagios mode=0644
  become: yes
  notify:
    - reload nagios

- name: Config Nagios | create sms log path
  file: path=/usr/local/nagios/var state=directory
  become: yes
