---
vars:
  config_kvm_virtual_networks: true
  config_nfs_mounts: true  #defines if NFS mountpoints should be mounted from nfs_mounts
  config_nfs_permissions: false  #defines if nfs mountpoints should have permissions set or not...this defaults to root
  kvm_virtual_networks:
  - name: DEFAULT_VLAN4
    mode: bridge
    bridge_name: vmbr2
    autostart: true
    state: active  #options are active, inactive, present and absent
nfs_mounts:
  - server: 10.12.10.201
    export: /volume1/kvm
    mount_options: hard,intr,nfsvers=3,tcp,bg,_netdev,auto,nolock
    mountpoint: /mnt/nfs
# tasks file for ansible-kvm
- include: hw_virtualization_check.yml

- include: kvm.yml

- include: config_kvm.yml
  tags:
    - config_kvm
#  when: config_kvm is defined and config_kvm

- include: nfs.yml
  tags:
    - config_nfs
  when: (config_nfs_mounts is defined and config_nfs_mounts) and nfs_mounts is defined

- include: users.yml
  tags:
    - config_users
  when: (config_kvm_users is defined and config_kvm_users) and kvm_users is defined

- include: config_ssh.yml
  tags:
    - config_ssh
  when: allow_root_ssh is defined and allow_root_ssh

- include: config_virtual_networks.yml
  tags:
    - config_virtual_networks
  when: (config_kvm_virtual_networks is defined and config_kvm_virtual_networks) and kvm_virtual_networks is defined
