---
wrappings:
  - "ps1 = powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -InputFormat None -File scripts\\NagiosWrapper.ps1 scripts\\%SCRIPT% %ARGS%"
  - "bat = scripts\\%SCRIPT% %ARGS%"
  - "vbs = cscript.exe //T:30 //NoLogo scripts\\lib\\wrapper.vbs %SCRIPT% %ARGS%"
  - "rb = scripts\\ruby.bat scripts\\%SCRIPT%"
command_timeout: 60
timeout: 30
sshd_enabled: true
motd_enabled: true
ntp_enabled: true
ntp_source:
  - "0.nl.pool.ntp.org"
  - "1.nl.pool.ntp.org"
  - "2.nl.pool.ntp.org"

time_zone: "Europe/Amsterdam"
manage_yum: false
manage_packages: true
manage_tuning: true
manage_vmware: true
__yum_managed_repos:
  - base
  - optional
  - epelrepo
  - redhat
yum_extra_repositories: {}
# Remove unmanaged repos
yum_purge_unmanaged: True
group_yum_managed_repos: []
