---
# tasks file for iis

    - name: Install IIS
      win_feature:
        name: "Web-Server"
        state: present
        restart: no
        include_sub_features: no
        include_management_tools: yes
