---
# defaults file for common-lin
ntp_timezone: Europe/Amsterdam
ntp_servers: 
  - nl.pool.org

resolv_search: sentia.net
resolv_nameservers:
  - 62.179.104.196
  - 213.46.228.196

nrpe_allowed_hosts: "10.1.2.3,10.1.0.1"

network_ether_interfaces: []
network_bridge_interfaces: []
network_bond_interfaces: []
