---
- name: Write Ansible Activity File
  raw: 'echo "Ansible Ran" > c:\scripts\AnsibleRan.log'
  
- include: nsclient.yml
- include: 7zip.yml
- include: npp.yml
- include: sysinternals.yml
- include: wireshark.yml
- include: ie.yml
