---
# tasks file for common-win
# http://www.nsclient.org/files/released/NSCP-0.4.3.131-x64.msi
# Install an MSI file
#
- name: create temp dir
  win_file: path=C:\tmp state=directory

- name: test stat module on msi file
  win_stat: path='C:\tmp\NSCP-0.4.3.131-x64.msi'
  register: stat_msi_file

- name: download nsclient
  win_get_url:
    url: 'http://sen-ans-g1/repo/NSCP-0.4.3.131-x64.msi'
    dest: 'C:\tmp\NSCP-0.4.3.131-x64.msi'
  when: not stat_msi_file.stat.exists

- name: test stat module on nsclient dir
  win_stat: path='C:\Program Files\NSClient++\nsclient.ini'
  register: stat_nsclient_file

- name: install nsclient
  raw: 'msiexec /qn /l* log.txt /i C:\tmp\NSCP-0.4.3.131-x64.msi ADDDEFAULT=ALL ALLOWED_HOSTS=127.0.0.2 ADDLOCAL=ALL'
  when: not stat_nsclient_file.stat.exists

- name: copy common checks
  win_copy: src=/home/ansible/ansible/teams/charlie/common/Nagios/NSClient/ClientPlugins/ dest=c:/Progra~1/nsclient++/scripts/

- name: dir listing checks
  raw: 'dir /b "C:\Program Files\NSClient++\scripts\check_*" "C:\Program Files\NSClient++\scripts\fix_*"'
  register: dir_listing_checks

- name: configure nsclient
  win_template: src=nsclient.j2 dest='C:\Program Files\NSClient++\nsclient.ini'
  notify:
    - restart nsclient
