---
# tasks file for common-win
# Install an MSI file
#
- name: create temp dir
  win_file: path=C:\tmp state=directory

- name: test stat module on msi file
  win_stat: path='C:\tmp\SysinternalsSuite.zip'
  register: stat_msi_file

- name: download sysinternals 
  win_get_url:
    url: 'https://download.sysinternals.com/files/SysinternalsSuite.zip'
    dest: 'C:\tmp\SysinternalsSuite.zip'
  when: not stat_msi_file.stat.exists

- name: test stat module on sysinternals dir
  win_stat: path="C:\Windows\Sysinternals\procmon.exe"
  register: stat_sysinternals_file

- name: install sysinternals 
  raw: '"C:\Program Files\7-zip\7z.exe" e C:\tmp\SysinternalsSuite.zip -oC:\Windows\Sysinternals'
  when: not stat_sysinternals_file.stat.exists

- name: set path
  raw: 'setx /M PATH "%PATH%;C:\Windows\Sysinternals"'
  when: not stat_sysinternals_file.stat.exists
  
