---
# tasks file for common-win
# Install an MSI file
#
- name: create temp dir
  win_file: path=C:\tmp state=directory

- name: test stat module on msi file
  win_stat: path='C:\tmp\Wireshark-win64-1.12.7.exe'
  register: stat_msi_file

- name: download wireshark
  win_get_url:
    url: 'http://sen-ans-g1/repo/Wireshark-win64-1.12.7.exe'
    dest: 'C:\tmp\Wireshark-win64-1.12.7.exe'
  when: not stat_msi_file.stat.exists

- name: test stat module on wireshark dir
  win_stat: path='C:\Program Files\Wireshark\Wireshark.exe'
  register: stat_wireshark_file

- name: install wireshark
  raw: 'C:\tmp\Wireshark-win64-1.12.7.exe /S'
  when: not stat_wireshark_file.stat.exists

