---
# defaults file for ansible-kvm
allow_root_ssh: false  #defines if ssh should be configured to allow root logins...mainly for managing KVM/Libvirt remotely using virt-manager or other.
config_kvm: true  #defines if kvm/libvirt should be configured
config_kvm_users: false  #defines if kvm_users should be added to libvirtd for managing KVM
config_kvm_virtual_networks: false  #defines if kvm virtual networks should be configured...if set to true ensure that your underlying bridges have been created.
config_nfs_mounts: true  #defines if NFS mountpoints should be mounted from nfs_mounts
config_nfs_permissions: false  #defines if nfs mountpoints should have permissions set or not...this defaults to root
enable_libvirtd_syslog: false
enable_kvm_mdns: false  #defines if libvirt should be advertised over mDNS - Avahi...default is false.
enable_kvm_tcp: false  #defines if unencrypted tcp connections are desired...default is false
enable_kvm_tls: true  #defines if remote tls connections are desired...default is true.
kvm_users:
  - remote
kvm_virtual_networks:
  - name: DEFAULT_VLAN2
    mode: bridge
    bridge_name: vmbr2
    autostart: true
    state: active  #options are active, inactive, present and absent
nfs_mounts:
  - server: 10.12.10.201
    export: /volume1/kvm
    mount_options: hard,intr,nfsvers=3,tcp,bg,_netdev,auto,nolock
    mountpoint: /mnt/kvm
