---
nrpe_commands:
  - command[check_users]=/usr/lib64/nagios/plugins/check_users -w 5 -c 10
  - command[check_load]=/usr/lib64/nagios/plugins/check_load -w 15,10,5 -c 30,25,20
  - command[check_disk]=/usr/lib64/nagios/plugins/check_disk -w 10% -c 5% -r '' -l
  - command[check_swap]=/usr/lib64/nagios/plugins/check_swap -w 60% -c 15% 
  - command[check_zombie_procs]=/usr/lib64/nagios/plugins/check_procs -w 5 -c 10 -s Z
  - command[check_total_procs]=/usr/lib64/nagios/plugins/check_procs -w 150 -c 300 
  - command[check_ntp_time]=/usr/lib64/nagios/plugins/check_ntp_time -H 10.128.20.68
  - command[uptime]=/usr/bin/uptime
