---
# tasks file for webapp_cmdb

- name: PHPBrew | Install the prereq packages
  yum:
    name:   "{{ item }}"
    state:  installed
  with_items: phpbrew_pkgs
  sudo: yes

- name: PHPBrew | Check Symlink
  stat: path=/usr/lib/libssl.so
  register: libssl_st
  
- name: PHPBrew | Check Symlink
  stat: path=/usr/lib/libcrypto.so
  register: libcrypto_st
 
- name: PHPBrew | Symlink PreReq 
  raw: ln -s /usr/lib64/libssl.so /usr/lib/libssl.so
  become: yes
  when: not libssl_st.stat.exists

- name: PHPBrew | Symlink PreReq
  raw: ln -s /usr/lib64/libcrypto.so /usr/lib/libcrypto.so
  become: yes
  when: not libcrypto_st.stat.exists
 
- name: PHPBrew | Download 
  raw: curl -L -O https://github.com/phpbrew/phpbrew/raw/master/phpbrew
  become: yes

- name: PHPBrew | Copy 
  raw: cp phpbrew /usr/bin
  become: yes

- name: PHPBrew | Enable 
  raw: chmod a+x /usr/bin/phpbrew
  become: yes

- name: PHPBrew | Check init directory
  stat: path=/root/.phpbrew
  become: yes
  register: initdir_st

- name: PHPBrew | Create init directory
  file: path=/root/.phpbrew state=directory
  become: yes
  when: not initdir_st.stat.exists

- name: PHPBrew | Init 
  raw: phpbrew init
  become: yes

- name: PHPBrew | Stat Updates
  stat: path=/root/.phpbrew/php-releases.json
  register: updates_st
  become: yes

- name: PHPBrew | Update 
  raw: phpbrew update --old
  become: yes
  when: not updates_st.stat.exists

- name: PHPBrew | Init File for Root
  template: src=init.j2 dest=/root/.phpbrew/init
  become: yes

- name: PHPBrew | Add PHPBrew.rc to .bashrc
  lineinfile: dest=/root/.bashrc line='source ~/.phpbrew/bashrc'
  become: yes

#- name: PHPBrew | Install version 
#  raw: phpbrew install --old 5.3.23
#  become: yes

- name: PHPBrew | Install file
  template: src=installphp.j2 dest=/root/installphp.sh owner=root group=root mode="u+rwx,g+rx,o+rx"
  become: yes

- name: PHPBrew | Install with script
  script: /root/installphp.sh
  become: yes
