---
# vars file for webapp_wwa

#developers who get SSH access to these machines

sshusers:
  - name: steven
    key: "{{ lookup('file', 'steven_laptop_rsa_id.pub') }}"
  - name: steven
    key: "{{ lookup('file', 'steven_relay_rsa_id.pub') }}"
  - name: hans
    key: "{{ lookup('file', 'hans_laptop_rsa_id.pub') }}"
  - name: hans
    key: "{{ lookup('file', 'hans_relay_rsa_id.pub') }}"

sshgroup: abergineit_admin

yum_pkgs:
  - mariadb
  - nano
  - php-pecl-apcu
  - memcached
  - php-soap