---
# tasks file for install_ansible

- name: epel | install epel package if os is redhat
  yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present disable_gpg_check=yes
  become: yes
  when: ansible_distribution == 'RedHat'

- name: epel | install epel package
  yum: state=present pkg=epel-release
  become: yes
  when: ansible_distribution == 'CentOS'

- name: Create Ansible user
  user: name=ansible comment="Ansible User"
  become: yes

- name: edit sudoers for ansible
  lineinfile: dest=/etc/sudoers state=present regexp='^ansible ALL\=' line='ansible ALL=(ALL) NOPASSWD:/bin/su' validate='visudo -cf %s'
  become: yes

- name: Install pip
  yum:
    pkg={{ item }}
    state=present
  with_items:
    - gcc
    - python-devel
    - python-pip
    - krb5-devel
    - sshpass
  become: yes

- name: Install ansible 1.9.3
  pip: name=ansible version=1.9.3
  become: yes

- name: Install pywinrm
  pip: name=pywinrm state=latest
  become: yes

- name: Install kerberos
  pip: name=kerberos state=latest
  become: yes
