---
# tasks file for install_sadis
- name: Install dependency
  yum:
    pkg={{ item }}
    state=present
  with_items:
    - openssl-devel
    - ruby
    - ruby-devel
    - gcc-c++
    - git
  become: yes

- name: create sadis log directory
  action: file path=/var/log/sadis/ state=directory owner=ansible mode=0755
  become: yes

- name: create sadis directory
  action: file path=/etc/sadis/ state=directory owner=ansible mode=0755
  become: yes

- name: check if sadis is installed
  shell: gem list ^sadis$ | awk {'print $2'} | cut -d'(' -f2 | cut -d')' -f1
  register: sadis_installed_version
  changed_when: False

- name: Copy sadis gem
  copy: src=sadis-{{ sadis.version }}.gem dest=/tmp/sadis-{{ sadis.version }}.gem owner=root group=root mode=0644
  become: yes

- name: uninstall sadis if new version
  gem: name=sadis state=absent
  become: yes
  when: sadis_installed_version.stdout != '{{ sadis.version }}'

- name: Install sadis gem
  gem: name=sadis gem_source=/tmp/sadis-{{ sadis.version }}.gem state=present user_install=no 
  become: yes
  when: sadis_installed_version.stdout != '{{ sadis.version }}'
  notify:
  - restart sadisd

- name: systemd sadis startup script
  become: yes
  copy:
    src: systemd/sadisd.service
    dest: /lib/systemd/system/
    mode: 0644
  notify:
  - reload systemd

- name: enable sadis on startup
  file:
    src: /usr/lib/systemd/system/sadisd.service
    dest: /etc/systemd/system/multi-user.target.wants/sadisd.service
    state: link
    force: yes

- name: create config file
  template:
    src=config.yml.j2
    dest=/etc/sadis/config.yml
    owner=ansible
    mode=0600
  notify:
    - restart sadisd

- name: be sure sadis is running and enabled
  service: name=sadisd enabled=yes state=started
  become: yes
