---
# tasks file for webapp_bba
  - include_vars: extravars.yml

  - win_template: src=webapibba.j2 dest=D:\wwwroot\API\web.ansible.config
  - win_template: src=webbobba.j2 dest=D:\wwwroot\BackOffice\web.ansible.config
  - win_template: src=webssbba.j2 dest="D:\wwwroot\BBA Selfservice\web.ansible.config"
  - win_template: src=webssiam.j2 dest="D:\wwwroot\IAM Selfservice\web.ansible.config"

# Includes
#- include: win_get_url.yml
