---
# Various Windows commands

- name: Stat MSSQL exe
    win_stat: path='D:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\Binn\sqlservr.exe'
    register: stat_mssql_exe

  - name: Stat MSSQL iso 
    win_stat: path='C:\scripts\SW_DVD9_SQL_Svr_Standard_Edtn_2014w_SP1_64Bit_English_-2_MLF_X20-29010iso'  
    register: stat_mssql_iso
#    when: not stat_mssql_exe.stat.exists

  - name: Run raw test
    raw: echo "test" > C:\Scripts\test.log

  - win_copy: src=SQL-2014.ini dest=c:\scripts\SQL-2014.ini
  - win_copy: src=Install-SQL2014.ps1 dest=c:\scripts\Install-SQL2014.ps1

  - name : Run SQL2014 install
    script : Install-SQL2014.ps1

  - name : Can service be named    
    win_service:
      name: w3svc
      start_mode: auto, manual, disabled
      state: started, stopped, restarted

  - name: Download MSSQL 2014 iso
    win_get_url: 
     url: 'http://sen-ans-g1/repo/SW_DVD9_SQL_Svr_Standard_Edtn_2014w_SP1_64Bit_English_-2_MLF_X20-29010.iso'
     dest: 'C:\Scripts\SW_DVD9_SQL_Svr_Standard_Edtn_2014w_SP1_64Bit_English_-2_MLF_X20-29010.iso'
    when: not stat_mssql_iso.stat.exists

 vars_prompt:

  - name: "some_password"
    prompt: "Enter password"
    private: yes

  - name: "release_version"
    prompt: "Product release version"
    private: no

- name: Install IIS
      win_feature:
        name: "Web-Server"
        state: present
        restart: no
        include_sub_features: no
        include_management_tools: yes