---
- name: restart sshd
  service: name=sshd state=restarted
  become: yes
- name: restart ntpd
  service: name=ntp state=restarted
  become: yes
- name: reload ntp
  service: name=ntp state=restarted
  become: yes
- name: clean_yum_cache
  command: yum clean all
  args:
    warn: false
