---
- include: check-variables.yml
- include: resolv.yml
- include: yum_repo.yml
- include: ntp-CentOS.yml
  #when: "ansible_distribution == 'CentOS'"
- include: motd-CentOS.yml
  when: "ansible_distribution == 'CentOS'"
- include: snmpd.yml
- include: sshd.yml
- include: users.yml
- include: nrpe.yml
- include: selinux.yml
- include: cron.yml
- include: networking.yml
- include: logrotate.yml
