---
- name: ntp | stop ntp server
  service: name=ntp state=stopped

- name: ntp | disable ntp
  service: name=ntp enabled=no

- name: ntp | set timezone
  file:
    src: "/usr/share/zoneinfo/{{ ntp_timezone }}"
    dest: "/etc/localtime"
    state: link
    force: yes
  become: yes
