---
- name: openssh-server | install openssh-server
  yum: state=present pkg=openssh-server
  become: yes

- name: openssh-server | configure openssh-server
  copy: src=sshd_config.conf dest=/etc/ssh/sshd_config.conf owner=root group=root mode=0600 backup=yes
  notify:
    - restart sshd
  become: yes
