---
- group: name=git state=present
  become: yes
- group: name=charlie_admin state=present
  become: yes
- group: name={{ item }} state=present
  with_items: sshusers
  become: yes

- user: name={{ item }} group=charlie_admin
  with_items: sshusers
  become: yes

- name: create key directory
  action: file path=/home/{{ item }}/.ssh/ state=directory
    owner={{ item }} group={{ item }} mode=0700
  with_items: sshusers
  become: yes

- name: upload user key
  copy: src={{ item }}_id_rsa.pub dest=/home/{{ item }}/.ssh/authorized_keys owner={{ item }} group={{ item }} mode=0600 backup=no
  with_items: sshusers
  become: yes

- name: edit sudoers
  lineinfile: dest=/etc/sudoers state=present regexp='^%charlie_admin ALL\=' line='%charlie_admin ALL=(ALL) NOPASSWD:/bin/su' validate='visudo -cf %s'

- name: edit sudoers for ansible user
  lineinfile: dest=/etc/sudoers state=present regexp='^ansible ALL\=' line='ansible ALL=(ALL) NOPASSWD: ALL' validate='visudo -cf %s'
