---
# tasks file for app_tentacle +++++
- include: install.yml
#- include: configure.yml
- win_template: src=configure_tentacle.j2 dest="C:\scripts\configure_tentacle.cmd"
- raw: 'C:\\scripts\\configure_tentacle.cmd'

#- win_template: src=configure_tentacle.j2 dest="C:\scripts\remove_tentacle.cmd"
#- raw: 'C:\\scripts\\remove_tentacle.cmd'


