---
# tasks file for app_tentacle +++++
#- include: install.yml

- win_template: src=configure_tentacle.j2 dest="{{ octopus.tentacleconfdest }}"
  when: octopus.tentacleconfigure

- raw: 'C:\\scripts\\configure_tentacle.cmd'
  when: octopus.tentacleconfigure

#- win_template: src=configure_tentacle.j2 dest="C:\scripts\remove_tentacle.cmd"
#- raw: 'C:\\scripts\\remove_tentacle.cmd'


