---
# tasks file for app_tentacle +++++
- include: install.yml

- win_template: src=configure_tentacle.j2 dest="{{ octopus.tentacleconfdest }}"
  when: octopus.tentacleconfigure

- raw: '{{ octopus.tentacleconfdest }}'
  when: octopus.tentacleconfigure

-name: Remove Tentacle Config
 win_template: src=remove_tentacle.j2 dest="{{ octopus.tentacleremoveconfdest }}"
 raw: '{{ octopus.tentacleremoveconfdest }}'
 when: octopus.tentacleremoveconfig


