---
# tasks file for app_tentacle +++++
#- include: install.yml

- win_template: src=configure_tentacle.j2 dest="C:\\scripts\\configure_tentacle.ps1"
  #when: octopus.tentacleconfigure

- raw: 'C:\\scripts\\configure_tentacle.ps1'
  #when: octopus.tentacleconfigure

#- win_template: src=configure_tentacle.j2 dest="C:\scripts\remove_tentacle.cmd"
#- raw: 'C:\\scripts\\remove_tentacle.cmd'


