---
- name: Stop rsyslog service
  service: name=rsyslog state=stopped enabled=no
  register: rsyslog_stopped

- name: Uninstall rsyslog
  yum: name=rsyslog state=absent
  register: rsyslog_uninstalled

- name: Install syslog-ng
  yum: name=syslog-ng state=present
  register: syslog-ng_installed

- name: Default configuration file
  template:
    src=syslog-ng.conf
    dest=/etc/syslog-ng/syslog-ng.conf
    owner=root
    group=root
    mode=644

- name: Update network configuration file
  template:
    src=network.j2
    dest=/etc/syslog-ng/conf.d/network.conf
    owner=root
    group=root
    mode=0644
  notify:
    - reload syslog_ng
