---
# tasks file for cacti
- name: Install prereqs
  yum:
    pkg={{ item }}
    state=present
  with_items:
    - php-mysql
    - php-pear
    - php-common
    - php-gd
    - php-devel
    - php
    - php-mbstring
    - php-cli
    - php-snmp
    - net-snmp-utils
    - net-snmp-libs
    - rrdtool
  become: yes

- name: Install cacti
  yum:
    pkg={{ item }}
    state=present
  with_items:
    - cacti
  become: yes

- name: check if Cacti DB exists
  shell: mysql -e "show databases;"
  ignore_errors: true
  register: databases
  changed_when: databases.stdout == 1
  become: yes

- name: Create cacti user
  user: name=cacti comment="Cacti user for poller process and configuration"
  become: yes

- name: Create database cacti
  mysql_db: name=cacti state=present
  become: yes

- name: Grants for user cacti
  mysql_user: name=cacti password={{ cacti_db_password }} priv=cacti.*:ALL state=present
  become: yes

- name: Populate Cacti database
  mysql_db: name=cacti state=import target=/usr/share/doc/cacti-0.8.8b/cacti.sql
  when: not (databases.stdout.find('cacti'))
  become: yes

- name: Create db.php
  template:
    src=db.php.j2
    dest=/etc/cacti/db.php
    owner=root
    group=root
    mode=0644
  become: yes

- name: downtime_sched | modify file downtime_job.pl
  replace: dest=/etc/httpd/conf.d/cacti.conf regexp='Require host localhost' replace='Require all granted'
  become: yes

- name: set poller cron
  cron:
    name="Cacti poller cron"
    state=present
    user="cacti"
    minute="*/5"
    hour="*"
    day="*"
    month="*"
    job="php /usr/share/cacti/poller.php 2>&1 >/dev/null"
  become: yes
