---
- name: create temp dir
  win_file: path='C:\\tmp' state=directory

- name: test stat module on msi file
  win_stat: path='C:\\tmp\\7z1506-x64.exe'
  register: stat_msi_file

- name: download 7zip
  win_get_url:
    url: 'https://repo.atbank.nl/artifacts/7zip/7z1506-x64.exe'
    dest: 'C:\tmp\7z1506-x64.exe'
    skip_certificate_validation: yes
  when: not stat_msi_file.stat.exists

- name: test stat module on 7zip dir
  win_stat: path='C:\\Program Files\\7-Zip\\7zFM.exe'
  register: stat_7zip_file

- name: install 7zip
  raw: 'C:\tmp\7z1506-x64.exe /S'
  when: not stat_7zip_file.stat.exists
