---
  - name: ntp | Install ntp package
    apt: name=ntp state=present
    ignore_errors: yes
    become: yes
  - name: ntp | Set timezone
    file: src="/usr/share/zoneinfo/{{ time_zone }}" dest="/etc/localtime" state=link force=yes
    become: yes
  - name: ntp | Set NTP servers
    template: src=ntp.conf.Ubuntu.j2 dest=/etc/ntp.conf
    notify:
      - reload ntp
    become: yes
  - name: ntp | create dir for step-tickers
    file:
      path: /etc/ntp
      state: directory
  - name: ntp | Set NTP step-tickers
    template: src=step-tickers.Ubuntu.j2 dest=/etc/ntp/step-tickers
    notify:
      - reload ntp
    become: yes
  - name: ntp | Enable ntpd service
    service: name=ntp state=started enabled=yes
    become: yes
