---
# tasks file for int_rsm-cmdb
- name: Stat Xampp exe 
  win_stat: path='C:\Scripts\xampp-win32-1.7.2.exe'
  register: stat_xampp_exe

- name: Download Xampp 1.7.2
  win_get_url: 
   url: 'http://sen-ans-g1/repo/xampp-win32-1.7.2.exe'
   dest: 'C:\Scripts\xampp-win32-1.7.2.exe'
  when: not stat_xampp_exe.stat.exists