---
- name: create temp directory
  win_file:
    path: 'C:\\tmp'
    state: directory
  tags: createdir

- name: test stat module on source exe file
  win_stat: path='C:\\tmp\\NDP452-KB2901907-x86-x64-AllOS-ENU.exe'
  register: stat_exe_file

- name: download source
  win_get_url:
    url: 'http://repo.atbank.nl/artifacts/dotnet/NDP452-KB2901907-x86-x64-AllOS-ENU.exe'
    dest: 'C:\\tmp\\NDP452-KB2901907-x86-x64-AllOS-ENU.exe'
  when: not stat_exe_file.stat.exists

- name: test stat module on .NET dir
  win_stat: path='C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\aspnet_compiler.exe'
  register: stat_dotnet_file

- name: install .NET Framework 4.5.2
  raw: 'c:\\tmp\\NDP452-KB2901907-x86-x64-AllOS-ENU.exe /q /norestart'
  when: not stat_dotnet_file.stat.exists

- name: clean up files
  win_file:
    path: 'C:\\tmp\NDP452-KB2901907-x86-x64-AllOS-ENU.exe'
    state: absent
  when: stat_exe_file.stat.exists
  tags: cleanup
