---

- name: Install PHP mod
  yum: name=php state=present
  become: yes

- name: Install PHP common mods
  yum: name=php-gd state=present
  become: yes

- name: Install PHP common mods
  yum: name=php-mcrypt state=present
  become: yes

- name: set date.timezone in php.ini
  replace: dest=/etc/php.ini regexp=';date.timezone =' replace='date.timezone = "Europe/Amsterdam"'
  notify:
    - reload httpd
  become: yes

- name: Add PHP mime type
  replace: dest=/etc/httpd/conf/httpd.conf regexp="^\s+AddType text/html .shtml$" replace="    AddType text/html .shtml .php"
  notify:
    - reload httpd
  become: yes
