---
yum_repositories:
  base:
    name: base
    description: Sentia RHEL 7 - x86-64
    baseurl: http://repo.sentia.nl/mrepo/rhel7Server-x86_64/RPMS.os
    enabled: yes
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
    gpgcheck: yes

  optional:
    name: optional
    description: Sentia RHEL 7 - x86-64
    baseurl: http://repo.sentia.nl/mrepo/rhel7Server-x86_64/RPMS.optional
    enabled: yes
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
    gpgcheck: yes

  epelrepo:
    name: epelrepo
    description: Epel - x86-64
    baseurl: http://repo.sentia.nl/mrepo/rhel7Server-x86_64/RPMS.elrepo
    enabled: yes
    gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    gpgcheck: yes

packages_absent:
  - tuned
  - aic94xx-firmware
  - alsa-firmware
  - alsa-tools-firmware
  - atmel-firmware
  - b43-openfwwf
  - bfa-firmware
  - ipw2100-firmware
  - ipw2200-firmware
  - ivtv-firmware
  - iwl100-firmware
  - iwl1000-firmware
  - iwl3945-firmware
  - iwl4965-firmware
  - iwl5000-firmware
  - iwl5150-firmware
  - iwl6000-firmware
  - iwl6000g2a-firmware
  - iwl6050-firmware
  - iwl7265-firmware
  - libertas-usb8388-firmware
  - ql2100-firmware
  - ql2200-firmware
  - ql23xx-firmware
  - ql2400-firmware
  - ql2500-firmware
  - rt61pci-firmware
  - rt73usb-firmware
  - xorg-x11-drv-ati-firmware
  - zd1211-firmware
  - iwl105-firmware.noarch
  - iwl135-firmware.noarch
  - iwl2000-firmware.noarch
  - iwl2030-firmware.noarch
  - iwl3160-firmware.noarch
  - iwl6000g2b-firmware.noarch
  - iwl7260-firmware.noarch

packages_present:
  - sudo
  - vim
  - wget
  - curl
  - rsync
  - mailx
  - mlocate
  - net-snmp
  - bc
  - telnet
  - lsof
  - logwatch
  - tree
  - screen
  - nc
  - xinetd
  - net-tools
  - psmisc
  - unzip
  - open-vm-tools
  - epel-release

snmp:
  package_name: net-snmp
  package_version: latest

  syslocation: localhost
  syscontact: root@localhost
  createuser: snmp
  createuserpass: not configured
  rouser: not configured
  rocommunity: not configured
