---
- name: create temp dir
  win_file:
    path: 'C:\\tmp'
    state: directory
  tags: createdir

- name: Download DC install script
  win_template:
    src: subDomainDC.ps1.j2
    dest: 'C:\\tmp\\subdomainDC.ps1'
  tags: copy

- name: install Domain Controller Role from script
  raw: powershell -File 'C:\\tmp\\subdomainDC.ps1'
  tags: install

- name: test stat module on scripts
  win_stat:
    path: 'C:\\tmp\\subDomainDC.ps1'
  register: stat_subdomaindc_script
  tags: cleanup

- name: clean up files
  win_file:
    path: 'C:\\tmp\subdomainDC.ps1'
    state: absent
  when: stat_subdomaindc_script.stat.exists
  tags: cleanup
